### PR TITLE
Fix issue 114: hostname resolves to 127.0.0.1

### PR DESCRIPTION
**Pull request by robpoyntz**
Previous patch submitted by ShaunParker is now stale. Submitting new patch that resolves this issue when working in a docker environment.

### CODE REVIEW

**Comment by Keksike** [comment]
@AdrieanKhisbe & co., could this be merged? We are currently running into the same issue and this seems like a solid fix :)

Also thanks to robpoyntz for fixing!

**Comment by russellpekala** [comment]
@AdrieanKhisbe @Keksike yes I think this solves an issue we have too.  Would appreciate a merge.

**Comment by jurienhamaker** [comment]
Can this be merged yet?

**Comment by striker1a** [comment]
this works - please merge...

**Review by striker1a — APPROVED** [review]
This works - multiple people have confirmed. Please merge.

**Review by IainVM — APPROVED** [review]
Tested wit Docker Server Version: 20.10.2
Works

**Review by pd93 — APPROVED** [review]

**Comment by IainVM** [comment]
@AdrieanKhisbe bump in hopes to get this change in.

**Comment by akomarov-tkww** [comment]
Could you please merge this?

**Comment by godu** [comment]
I prefer use `new URL` instead of `Regex`.
I publish it in `serverless-offline-sqs@6.0.0`.
Thank you for your analysis :)

**Pull request closed without merging**
