### PR TITLE
Clean environment setup for sqs offline

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Minimize intervention on `process.env`,
and add integration test for env forwarding

Related: #102 and #20

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
Notes:
still a work in progress, will need to:
- check behavior for `useWorkerThreads` (cf #102)
- bump serverless-offline for integrations tests to pass after https://github.com/dherault/serverless-offline/pull/884 has land
- maybe more

**Comment by AdrieanKhisbe** [comment]
So far it's still a work in progress, will need to:
- check behavior for `useWorkerThreads` (cf #102)
- bump serverless-offline for integrations tests to pass after https://github.com/dherault/serverless-offline/pull/884 has land
- maybe more

**Comment by esetnik** [comment]
This is great progress. Thank you @AdrieanKhisbe for taking it on!

**Comment by godu** [comment]
Serverless-offline@10 no longer copies parent env vars to child processes.
We can close this PR.

**Comment by godu** [comment]
There is a new options [`localenvironment`](https://github.com/dherault/serverless-offline#localenvironment) from serverless-offline.

**Pull request closed without merging**
